#!/usr/bin/env bash
set -e
[ -n "$BOOTSTRAP_DEBUG" ] && set -x

banner()  { printf -- "-----> $*\n"; }
log()     { printf -- "       $*\n"; }
warn()    { printf -- ">>>>>> $*\n"; }
fail()    { printf -- "\nERROR: $*\n" ; exit 1 ; }

if ! command -v direnv >/dev/null ; then
  warn "the direnv command is not installed and helps in using"
  warn "this project."
  warn ""
  warn "please visit https://github.com/zimbatm/direnv for more details."
  warn ""
  warn "if you are on a mac and using homebrew, install it with:"
  warn ""
  warn "    $ brew install direnv"
  warn ""
  warn "follow the post-install instructions, and re-run $0"
  warn "\n"
fi


if ! command -v bundle >/dev/null ; then
  banner "Installing bundler gem"
  gem install bundler
fi

if ! bundle check >/dev/null ; then
  bundle_cmd="bundle install --path vendor/bundle --binstubs vendor/binstubs"
  banner "Running '$bundle_cmd'"
  $bundle_cmd
else
  log "Bundler up to date, skipping 'bundle install'"
fi

banner "Running 'berks install'"
"$(dirname $0)/../vendor/binstubs/berks" install

banner 'All ready!'
