#!/usr/bin/env bash
set -e
[ -n "$BOOTSTRAP_DEBUG" ] && set -x

banner()  { printf -- "-----> $*\n"; }
log()     { printf -- "       $*\n"; }
warn()    { printf -- ">>>>>> $*\n"; }
fail()    { printf -- "\nERROR: $*\n" ; exit 1 ; }

if ! command -v direnv >/dev/null ; then
  warn "The direnv command is not installed and helps in using"
  warn "this project."
  warn ""
  warn "Please visit https://github.com/zimbatm/direnv for more details."
  warn ""
  warn "If you are on a mac and using homebrew, install it with:"
  warn ""
  warn "    $ brew install direnv"
  warn ""
  warn "Follow the post-install instructions, and re-run $0"
  warn "\n"
fi

if ! command -v bundle >/dev/null ; then
  banner "Installing bundler gem"
  gem install bundler
fi

bundle_cmd="bundle install --path vendor/bundle --binstubs vendor/binstubs"
banner "Running '$bundle_cmd'"
$bundle_cmd
bundle clean

if ! command -v vagrant >/dev/null ; then
  fail "An installation of Vagrant could not be found, please install a package"
fi

banner "Checking for Vagrant"
if [[ "$(vagrant --version)" < "Vagrant version 1.1.0" ]] ; then
  fail "Only Vagrant versions 1.1.0 and up are supported, please update"
fi

banner "Checking for vagrant-berkshelf plugin"
if ! vagrant plugin list | grep -q '^vagrant-berkshelf ' >/dev/null ; then
  fail "Berkshelf Vagrant must be installed with: vagrant plugin install vagrant-berkshelf"
fi

banner "Checking for vagrant-omnibus plugin"
if ! vagrant plugin list | grep -q '^vagrant-omnibus ' >/dev/null ; then
  fail "vagrant-omnibus must be installed with: vagrant plugin install vagrant-omnibus"
fi

banner "Running 'berks install'"
"$(dirname $0)/../vendor/binstubs/berks" install

banner 'All ready!'
